scenes[0] = [
	["animation", "fadeIn", "detective", 180],
	["talk", "detective", "\"Mortin Addenworth\", huh?"],
	["talk", "detective", "That's a name I haven't heard in a long time."],
	["talk", "detective", "He was the victim of a murder case I had to investigate... around a year ago, I'd say. Turned up dead in his own mansion, the poor man."],
	["talk", "detective", "But I suppose you already knew that, since you're asking about him."],
	["talk", "detective", "You must be a journalist or something similar, isn't that right?"],
	["talk", "detective", "How do I know? Well, if you've come to me instead of the police, it's because you want some details on the case."],
	["talk", "detective", "So you're either a journalist, or a relative. And your clothes would look much more expensive if you were in the Addenworth family."],
	["talk", "detective", "Heh, no offense, of course. I'm just doing my job."],
	["talk", "detective", "In any case, you want to know the whole story, don't you?"],
	["talk", "detective", "... Sure, why not? Work has been scarce lately, and I have some time to kill."],
	["talk", "detective", "It all started when I received a call around noon, telling me to come over to Addenworth mansion, and fast. Of course, I immediately suspected there had been a murder."],
	["talk", "detective", "So I drove to the mansion. When I knocked on the door, a voice answered from the other side, as though it was waiting for me."],
	["animation", "fadeOut", "detective", 180],
	["talk", "butler", "May I help you?"],
	["talk", "detective", "Percival, it's me. Let me in."],
	["talk", "butler", "Oh, naturally, Mister Maverick. Let me open the door for you."],
	["animation", "fadeIn", "detective", 90],
	["animation", "fadeIn", "butler", 90],
	["talk", "butler", "We're fortunate that you were able to arrive so quickly, Mister Maverick. We are in dire need of your services here."],
	["talk", "detective", "Let me guess. A murder, isn't that right?"],
	["talk", "butler", "Most certainly, Mister Maverick. I'm afraid Lord Addenworth himself has passed away. We are all extremely afflicted by this loss."],
	["talk", "detective", "So Mortin has been killed, huh... Just like I thought. Have you called the police?"],
	["talk", "butler", "Not yet, Mister Maverick. Lady Addenworth requested that I wait for your arrival before calling anybody else."],
	["talk", "detective", "Okay, first things first. Where is she right now?"],
	["talk", "butler", "Lady Addenworth is reunited at the living room. Please, allow me to escort you there."]
];
