scenes[0] = [
	["animation", "fadeIn", ["detective"], 180],
	["talk", "detective", "\"Mortin Addenworth\", huh?"],
	["talk", "detective", "That's a name I haven't heard in a long time."],
	["talk", "detective", "The victim of a murder case I investigated... about 4 years ago, I'd say. Turned up dead in his own mansion, the poor man."],
	["talk", "detective", "But I suppose you already know that, since you're asking about him. Can't say I get a lot of questions about old cases like this one."],
	["talk", "detective", "You must be... a journalist or something? Not like I care, but you're sure as hell not a relative."],
	["talk", "detective", "Judging by those clothes you're wearing, you won't see as much money in your entire life as the Addenworths spend in a day."],
	["talk", "detective", "Heh, just doing my job. Don't take it personally."],
	["talk", "detective", "In any case... You said you wanted to know the story behind the case?"],
	["talk", "detective", "Normally I don't have a lot of patience for people like you, snooping around and digging up old cases like that..."],
	["talk", "detective", "Business has been dry lately, though, and I have some time to kill."],
	["talk", "detective", "Take a seat, kid. This is a long story."],
	["talk", "detective", "It all started when I got a call from a good friend of mine. \"Come to the Addenworth mansion, and quick\", she said."],
	["talk", "detective", "Right away, I knew that meant a new case to investigate."],
	["talk", "detective", "So I got to the mansion without wasting one more second. I knocked on the door, and a voice answered from the other side..."],
	["animation", "fadeOut", ["detective"], 180],
	["talk", "butler", "May I help you?"],
	["talk", "detective", "Percival, it's me. Let me in."],
	["talk", "butler", "Oh, naturally, Mister Maverick. Let me open the door for you."],
	["animation", "moveMapIcon", ["detective", "butler"], 1, {endPos: map.sections["entrance"]}],
	["animation", "fadeIn", ["detective", "butler", "map", "detectiveMap", "butlerMap"], 90],
	["talk", "butler", "We have been expecting you, mister Maverick. We are fortunate that you were able to arrive so quickly."],
	["talk", "butler", "As you were most likely anticipating, we are in dire need of your services here."],
	["talk", "detective", "So I've heard. A case for me, right?"],
	["talk", "butler", "That is correct. I'm afraid Lord Addenworth himself has been... well, to put it bluntly, murdered."],
	["talk", "detective", "So Mortin is the victim..."],
	["talk", "butler", "I am aware that you were close friends with him. If you would prefer a minute to..."],
	["talk", "detective", "No, it's all right. I have work to do. But I know this must be hard for the family... How is Rose doing?"],
	["talk", "butler", "None of us is quite sure how to react. It was a shocking event, no doubt. But Lady Addenworth requested that we call you immediately. I have also been instructed to wait for your arrival before informing the authorities."],
	["talk", "detective", "Good. Smart move. Those incompetent investigators would just trample all over the crime scene."],
	["talk", "detective", "Tell me, where is she now?"],
	["talk", "butler", "Lady Addenworth is reunited with miss DeLethe at the living room. Allow me to escort you there."],
	["animation", "moveMapIcon", ["detective", "butler", "widow", "guest"], 90, {endPos: map.sections["living_room"]}],
	["animation", "fadeIn", ["widowMap", "guestMap"], 90]
];
